server:
  address: localhost
  port: 9099
#  servlet:
#    context-path: "/${spring.application.api-version}"
spring:
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: hackathon-app-group
  application:
    api-version: v1
    name: pms-audit-api
  timezone: UTC

  profiles:
    active: dev

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/default_db
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

sonar:
  host:
    url: http://localhost:9000
  projectName: pms-audit-api
  projectKey: pms-audit-api
logging:
  file: ./logs/pms-audit-api.log

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

app:
  hackathon:
    key: key-pwd
    audit-topic: event-hackathon-app-user